apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kubernetesVersion: "v1.21"
kindV1Alpha4Cluster:
  nodes:
  - role: control-plane
  - role: worker

