name: CI

env:
  BUILD_VERSION: 0.2.0

# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master
    paths:
      - app/*
      - Dockerfile

jobs:
  dockerize:
    name: Dockerize the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Time
        id: ts
        uses: nanzm/get-time-action@v1.0
        with:
          format: "yyyy-MM-dd'T'HH:mm:ssZ"
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: epestov/replacer
          tags: ${{ env.BUILD_VERSION }}
          build_args: BUILD_DATE=${{ steps.ts.outputs.time }},VCS_REF=${{ env.GITHUB_SHA }},BUILD_VERSION=${{ env.BUILD_VERSION }}